apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amazon
  template:
    metadata:
      labels:
        app: amazon
    spec:
      containers:
      - name: amazon
        image: codersdiary/amazon:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: amazon-service
spec:
  type: NodePort
  selector:
    app: amazon
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001

