
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipkart-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flipkart
  template:
    metadata:
      labels:
        app: flipkart
    spec:
      containers:
      - name: amazon
        image: codersdiary/flipkart:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flipkart-service
spec:
  type: NodePort
  selector:
    app: flipkart
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
